const to = "A tó és környéke - A község déli részén mesterségesen kialakított, kellemes környezetben lévő jóléti tározó révén Gersekarát turisztikai értékek tekintetében a Vasvári kistérség egyik legjobb adottságokkal bíró települése. A 36,3 hektáros Sárvíz-tó, valamint két előtározója kedvelt kirándulóhely, horgászparadicsom. A tó vize alkalmas fürdőzésre és vízisportok űzésére, szépen gondozott partján kempingezésre is lehetőség van. Jelzett túra útvonal halad át a tó környékén. A tóparton büfé és vendéglátó egység szolgálják az idelátogató vendégek ellátását és kényelmét. A helyi természeti adottságokra építve egyre többen foglalkoznak a falusi vendéglátással.";

const millenium = "Millenniumi Emlékpark - A település központjában, a Fias-tó körüli tölgyes erdőben került kialakításra a község Millenniumi Emlékparkja. Itt több, faragott alkotás, pihenő pad került elhelyezésre. A Millenniumi Emlékparknak helyet adó terület a település északi részén fekvő úgynevezett „legelőerdő”-ként számon tartott tölgyerdő része. A területe 3563 m2, amely a mellette lévő Fias-tóval ex lege (törvénynél fogva) védett. A park építése 2001-ben, a millennium tiszteletére emelt szobrok elhelyezésével vette kezdetét.";

const karatfold = "Karátföldi-szőlőshegy - Gersekarát község lakói két szőlőhegyen gazdálkodnak, több család foglalkozik szőlőtermesztéssel, bortermeléssel és méhészkedéssel. A település karátföldi részén élő családok a település dél-nyugati határában lévő Bükkhegy lankás domboldalain műveltek régen és művelnek ma is szőlőt. A szőlőhegyen való gazdálkodás több száz éves múltra tekint vissza, ezt igazolják a ma is látható építészeti örökségelemek, a présházak és pincék (igaz néhol már csak maradványokban). Az utóbbi évtizedben megvalósult a gyönyörű panorámájú Bükkhegy nagy részének villamosítása. Ennek köszönhetően egyre több szőlősgazda újítja fel pincéjét, folytatja, illetve fejleszti a szőlőművelést és a bortermelést. A fontosabb hagyományos térségi szőlőfajták megegyeznek a közeli petőmihályfai szőlőhegyen termőkkel: Noah, Othello, Zalagyöngye, Vértescsillaga, Lakhegyi mézes, Cserszegi fűszeres, Merlot, Zweiger. A 2009-ben alakult Bükkhegyért Egyesület célul tűzte ki a szőlőhegyi kultúra felélesztését, a minőségi bortermelés ösztönzését és segítését, valamint a Bükkhegy területéhez tartozó szőlőhegy műemléki értékű présházainak, a haranglábnak és a kereszteknek a megmentését, a hagyományos szőlőhegyi környezet visszaállítását és megóvását.";

const peto = "Petőmihályfai-szőlőshegy - Gersekarát és Petőmihályfa között már jó ideje megtalálható „A Hegy”. A legkorábbi nyoma az itt működött hegyközségnek az 1727. április 22-én kihirdetett hegyi törvény, az Arcticulus. Ebben a birtokot átvevő Festetics Kristóf hirdettette ki az akkortól érvényes szabályokat. Bár a terület nem tartozik egyetlen hazai történelmi borvidékhez sem, ugyanakkor a szőlő- és borkultúra nagy hagyományokkal rendelkezik, elég, ha csak az építészeti örökségelemekre, présházakra, pincékre gondolunk. A fontosabb hagyományos térségi szőlőfajták a következők voltak: Noah, Othello, Zalagyöngye, Vértescsillaga, Lakhegyi mézes, Cserszegi fűszeres, Merlot, Zweiger. A XIX. század elején épült műemlékek a hegyben a 4 darab Pince-présház a Barkóca hegyen (a legkorábbi 1823-ban épült), a Boronafalas pince-présház a (Csuhás) Öreghegyen, a Hajlított pince-présház a Thorma dűlőn. Az utóbbi években több ilyen fatalpú, boronafalú épületet hoztak rendbe s ezek az építmények díszei a hegynek, felidézik a régmúlt idők vissza nem térő hangulatának zamatát. A Hegy gersei bejáratánál áll a Szent Bertalan kápolna. A XVIII. században, barokk stílusban épült kápolnát 1860 körül bővítették. Későbarokk oltárát 1779-ből a régi kápolnából helyezték át, harangja 1743-ból való. A kápolnától, a vasvári műút felé eső területen az egykori „Templom-tó”, majd láp terül el. Ez - érdekes növénytársulásával - beleillik a Vasi Hegyháton végighúzódó tóláncba, melynek szép példája a Gersekaráton megtekinthető Fias-tó is.";

const fiasto = "Fiastó tanösvény - A Fias-tó egyike a Vasi Hegyhát fennsíkján kialakult talajvíz által táplált, más élő vízforrással nem rendelkező tavaknak. Nyilvántartott láp, s mint ilyen, védelmet élvez. A régi térképeken tavunk területe nagyobbnak látszik. Egy részét lecsapolták, egy részét feltöltötték, ma a „fias” tónak már csak a „fia” van meg. Szomszédjáról dűlőnév maradt fenn: a Hóttó. A Fias-tó területének csak egészen kis felülete szabad víztükör. Nagyobb része zsombékos, náddal, gyékénnyel lepett terület. Környékén viszonylagos biztonságban megtalálható sok, a környékünkre jellemző növény- és állatfaj. Partja a kora tavaszi barka egyik lelőhelye, a védett agárkosbor apró virágait szintén itt figyelhetjük meg. A Fias-tó szigetein fűzfák állnak, melyek tartós szárazság idején a szárazföldön is megközelíthetőek. A tavat környékező erdőben megtalálható a kocsányos- és kocsánytalan tölgy és a gyertyán, tavasszal számos gombafaj lelőhelye. Nyári estéken a békakórusban, a tücskök ciripelésében, hajnalban az énekes madarak előadásaiban gyönyörködhet minden környéken lakó és idelátogató.";

const helytorteneti = "Helytörténeti Múzeum - Több helyi lakosnak volt dédelgetett álma egy helytörténeti gyűjtemény létrehozása, ahol lehetőség nyílik a község régmúltjába való bepillantásra, a régi időkben használt eszközök, berendezési tárgyak megismerésére. A Művelődési Házban működő helytörténeti klub koordinálásában számos régi használati eszköz és dísztárgy, valamint írásos anyag és fénykép került összegyűjtésre. Az elhelyezésük nem volt megoldott. A helyiek kezdeményezését segítve jött 2006-ban az AVOP LEADER pályázati felhívása. A projekt révén nagy részben eredeti állapotának megfelelően újult meg a régi „kanászház”. A rendelkezésre álló négy helyiségből egy szoba, egy konyha és egy kamra került kialakításra és berendezésre. A konyhában lévő kemence megmaradt, a későbbiekben ez alkalmas fűtésre és kenyér-, langallósütésre. Az épület mellett található egy kőkereszt, valamint egy szőlőlugas. A paraszti életvitelnek emléket állító berendezések és használati, valamint díszítő eszközök főként a benyújtott pályázat kapcsán kerültek beszerzésre, de emellett nagyon sok helyi lakos által felajánlott tárgy is megtalálható a házban. A helytörténeti gyűjtemény révén az érdeklődők számára interaktív foglalkozások tartására kerül sor, például a régi időben használt díszítő tárgyak és helyi paraszti ételek készítése.";

export default [
    ["http://i.imgur.com/hU0Nnvt.jpg", to],
    ["http://i.imgur.com/xwbnthq.jpg", to],
    ["http://i.imgur.com/lPldDmP.jpg", to],
    ["http://i.imgur.com/HuVS7ye.jpg", to],
    ["http://i.imgur.com/uA5fPr0.jpg", to],
    ["http://i.imgur.com/08js0xd.jpg", to],
    ["http://i.imgur.com/Q1TuLIn.jpg", to],
    ["http://i.imgur.com/IpSiDLT.jpg", to],
    ["http://i.imgur.com/CYPP4us.jpg", to],
    ["http://i.imgur.com/OVV6vKX.jpg", to],
    ["http://i.imgur.com/Oe7OiQy.jpg", to],
    ["http://i.imgur.com/RLNzgSB.jpg", to],
    ["http://i.imgur.com/rUAhAmp.jpg", to],
    ["http://i.imgur.com/pstspyi.jpg", to],
    ["http://i.imgur.com/5rg2keu.jpg", to],
    ["http://i.imgur.com/lFOHbcO.jpg", to],
    ["http://i.imgur.com/K9fzJzt.jpg", to],
    ["http://i.imgur.com/IG0Vqij.jpg", to],
    ["http://i.imgur.com/2lmsIRY.jpg", to],
    ["http://i.imgur.com/WoKDVCt.jpg", to],
    ["http://i.imgur.com/gt36cFm.jpg", to],
    ["http://i.imgur.com/1b6PSR1.jpg", to],
    ["http://i.imgur.com/p1J0mzm.jpg", to],
    ["http://i.imgur.com/vu7cjw2.jpg", to],
    ["http://i.imgur.com/ZzpZB7w.jpg", millenium],
    ["http://i.imgur.com/5pmhwwJ.jpg", millenium],
    ["http://i.imgur.com/ypR3uEy.jpg", millenium],
    ["http://i.imgur.com/eNBbaUW.jpg", millenium],
    ["http://i.imgur.com/LfpmEnK.jpg", millenium],
    ["http://i.imgur.com/RZ4xIBB.jpg", millenium],
    ["http://i.imgur.com/BgAI2nK.jpg", millenium],
    ["http://i.imgur.com/Dyhezrp.jpg", millenium],
    ["http://i.imgur.com/R1642L5.jpg", millenium],
    ["http://i.imgur.com/GoSvpzf.jpg", millenium],
    ["http://i.imgur.com/v8mtm55.jpg", karatfold],
    ["http://i.imgur.com/rgX0zS5.jpg", karatfold],
    ["http://i.imgur.com/8mKQdUt.jpg", karatfold],
    ["http://i.imgur.com/3pEob8P.jpg", karatfold],
    ["http://i.imgur.com/q3dlpTw.jpg", karatfold],
    ["http://i.imgur.com/1P9YkjO.jpg", karatfold],
    ["http://i.imgur.com/6sNuS8E.jpg", karatfold],
    ["http://i.imgur.com/3T9XjDv.jpg", karatfold],
    ["http://i.imgur.com/nXT50oq.jpg", karatfold],
    ["http://i.imgur.com/Dpdam2D.jpg", karatfold],
    ["http://i.imgur.com/pC3ujHZ.jpg", karatfold],
    ["http://i.imgur.com/ByTm6hn.jpg", karatfold],
    ["http://i.imgur.com/Ip3Z7k4.jpg", karatfold],
    ["http://i.imgur.com/xhDy6C2.jpg", peto],
    ["http://i.imgur.com/LSuk3mq.jpg", peto],
    ["http://i.imgur.com/6psF9cx.jpg", peto],
    ["http://i.imgur.com/UrK2YCa.jpg", peto],
    ["http://i.imgur.com/SbztGyz.jpg", peto],
    ["http://i.imgur.com/ydZY8kZ.jpg", peto],
    ["http://i.imgur.com/QeQCnCY.jpg", peto],
    ["http://i.imgur.com/uyOz0Jq.jpg", peto],
    ["http://i.imgur.com/pE6O8Uc.jpg", peto],
    ["http://i.imgur.com/LtUuR7k.jpg", peto],
    ["http://i.imgur.com/CEl0bk5.jpg", peto],
    ["http://i.imgur.com/q3r6uCB.jpg", peto],
    ["http://i.imgur.com/nzu7Xse.jpg", peto],
    ["http://i.imgur.com/jmjyNrx.jpg", peto],
    ["http://i.imgur.com/7rMKPI7.jpg", peto],
    ["http://i.imgur.com/cqnY2X4.jpg", peto],
    ["http://i.imgur.com/XvfVDl1.jpg", peto],
    ["http://i.imgur.com/LgwLQZK.jpg", peto],
    ["http://i.imgur.com/GAIsHqT.jpg", peto],
    ["http://i.imgur.com/56CzeFl.jpg", fiasto],
    ["http://i.imgur.com/mKNvZNp.jpg", fiasto],
    ["http://i.imgur.com/42ycpyB.png", fiasto],
    ["http://i.imgur.com/vBPCrNX.jpg", fiasto],
    ["http://i.imgur.com/AhfuVOK.jpg", fiasto],
    ["http://i.imgur.com/ztVlifU.jpg", fiasto],
    ["http://i.imgur.com/LruI2gZ.jpg", fiasto],
    ["http://i.imgur.com/NhUTAWr.jpg", fiasto],
    ["http://i.imgur.com/flZNgEP.jpg", fiasto],
    ["http://i.imgur.com/vjvO8vB.jpg", fiasto],
    ["http://i.imgur.com/vCmD02g.jpg", fiasto],
    ["http://i.imgur.com/5djhMM0.jpg", fiasto],
    ["http://i.imgur.com/oUDY4hv.jpg", fiasto],
    ["http://i.imgur.com/tIfTqkT.jpg", fiasto],
    ["http://i.imgur.com/Vh8atsk.jpg", fiasto],
    ["http://i.imgur.com/59Zd9rM.jpg", helytorteneti],
    ["http://i.imgur.com/BkK8VkD.jpg", helytorteneti],
    ["http://i.imgur.com/aCey7T6.jpg", helytorteneti],
    ["http://i.imgur.com/2ChipTA.jpg", helytorteneti],
    ["http://i.imgur.com/cmrslz8.jpg", helytorteneti],
    ["http://i.imgur.com/GYypJsC.jpg", helytorteneti],
    ["http://i.imgur.com/dXv5Kjl.jpg", helytorteneti],
    ["http://i.imgur.com/NsvZTmz.jpg", helytorteneti],
    ["http://i.imgur.com/tUES2yg.jpg", helytorteneti],
    ["http://i.imgur.com/1gUTTbH.jpg", helytorteneti],
    ["http://i.imgur.com/9bAFwMq.jpg", helytorteneti],
];
